#!/bin/sh

# Copyright (c) 2012, 2013 Michele Bini <michele.bini@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the version 3 of the GNU General Public License
# as published by the Free Software Foundation.

# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

println() {
    printf "%s
" "$*"
}

warn() {
    println "$0: $*" >&2
}

die() {
    warn "$*"
    exit 1
}

f="$1"

if [ -z "$f" ]; then
    if [ -f .uncommitted-patches ]; then
	f="$(tail -n1 .uncommitted-patches|sed "s/^Uncommit: //")"
	sed -i "$ d" .uncommitted-patches
    fi

    # Delete .uncommitted-patches if it's empty
    if [ -e .uncommitted-patches ]; then
	[ -s .uncommitted-patches ] || rm .uncommitted-patches
    fi
fi

if [ -z "$f" ]; then
    f="$(ls -R --sort=time|grep "[.]patch$"|head -n1)"
fi

[ -z "$f" ] && die "No patch files found!"

git am -3 "$f" && rm "$f"
